import React from 'react';
import AthleteProfile from './AthleteProfile';

const athleteData = [
 
  {
    fullName: 'Danny Royce',
    hometown: 'Midlothian, VA',
    currentResidence: 'Midlothian, VA',
    familyDetails: 'Wife-Brittany, 2 Daughters (Sloane 8, Chandler 4), cavalier king charles spaniel (Bear)',
    occupation: 'Lawyer',
    startTriathlon: 'It filled a void left by the end of my college swimming career. I grew to love the suffering required to be good. I love the challenge of squeezing all my training in without compromising my roles as the best husband and father I can be.',
    preferredDistance: 'Ironman',
    highlights: 'Definitely qualifying for Kona twice!!!',
    interests: 'People have other hobbies?!?! I love being a dad to athletic kids and I can’t wait to watch them develop and chase their dreams. I love being the dad that goes to all the practices and competitions. I also love collecting Air Jordans!',
    goals: 'To represent our team and sponsors in the best way possible. Success at home, in the community and on the race course.',
    additionalInfo: 'Excited to be on a co-ed team with athletes of all ages from all walks of life who are so accomplished in so many ways.',
    pictureUrl: '/images/DannyRoyce.jpg'
  },

  {
    fullName: 'Alden Basmajian',
    hometown: 'Richmond VA',
    currentResidence: 'Richmond VA',
    familyDetails: 'Married to Kim with three kids - Addison, Daniel, and Kensington. Two goldens - Leo and Aslan',
    occupation: 'High school math teacher',
    startTriathlon: '2012 for real; lived in Hoboken, NJ at the time and NY hosted their one and only ironman in the city. I wanted to get going so just jumped right in and went for it.',
    preferredDistance: 'Half Ironman',
    highlights: 'Racing Kona, crossing the finish line for the win at Rev3 Williamsburg with my kids, finishing #4 age group rankings in 2019, national champ in 2023 at half distance',
    interests: 'Playing piano, I love to cook',
    goals: 'Find motivation to push to new heights with the group',
    additionalInfo: '',
    pictureUrl: '/images/Alden2.jpeg'
  },
  {
    fullName: 'Norman Kim',
    hometown: 'Westford, MA',
    currentResidence: 'Westford, MA',
    familyDetails: 'Carolyn, wife of 30+ years; a daughter, Kristen, and a son, Justin',
    occupation: 'Toxicologist',
    startTriathlon: '1986; ran through high school; rowing team in college, triathlons post-college',
    preferredDistance: 'Long course',
    highlights: 'Completed numerous half-irons and 5 IMs including Kona twice',
    interests: 'Family, work, reading and training - not in any specific order',
    goals: 'Represent Team USA in Long Course Triathlon Worlds in Amsterdam',
    additionalInfo: 'To converse, train and race with top age group athletes',
    pictureUrl: '/images/NormanKim.jpg',
},

{
    fullName: 'Nik Reinert',
    hometown: 'Mertztown, PA',
    currentResidence: 'Pittsburgh, PA',
    familyDetails: 'Wife Lori, Corgi Buster Brown',
    occupation: 'Project Manager',
    startTriathlon: '2021, beat cancer and got a real kick in the pants to give competition one more try after bike racing in my younger years',
    preferredDistance: 'Ironman',
    highlights: '2023 USAT 140.6 National Champion, 6x USAC Track Cycling National Champion',
    interests: 'Bike racing and advocacy, fixing old cars, chess',
    goals: 'It is my first pro season so I am targeting MDot races, I would consider it a success if I can finish in the top half of the pro field at these events.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/NikReinart.jpg'
},
  {
    fullName: 'Adriene McCarthy',
    hometown: 'Windham, NH',
    currentResidence: 'Windham, NH',
    familyDetails: "Husband-Ken from Australia and two dogs names Margs and Duke. I have a lot of family in the area that we spend a lot of time with on the lake, up in the mountains, and out west where one of my sisters lives. We try to get back to Australia to visit Ken's family and friends as often as possible",
    occupation: 'Business owner- Pure Barre Nashua & Bedford, Boss Blow Dry Bar ',
    startTriathlon: 'I started in 2021. I had always known what Ironman was and had it in my mind that I would like to compete in the race someday. A close friend was the first person I actually knew who did an Ironman a few years prior, and I knew that it was something I wanted to pursue. In 2021, I completed my first half and full Ironman races (after learning to swim a bit better and buying a bike). I did not intent to do more than that, but fell in love with the sport and have since done 8 70.3 races and 2 full Ironman races. ',
    preferredDistance: 'Half and Full Ironman',
    highlights: '4th place at Western Ma 70.3 in 2023, racing in the 70.3 World Championship in St. George Utah in 2022',
    interests: 'I love being on the boat, waterskiing, spending time with my family and dogs, snowboarding and traveling ',
    goals: 'First place in my AG at a 70.3 race, qualify for and attend 70.3 World Championships in New Zealand',
    additionalInfo: 'I am thrilled to be a part of the Topgunz team!',
    pictureUrl: '/images/AdrienneMcCarthy.jpg'
  },
  {
    fullName: 'Evan Coronado',
    hometown: 'Sudbury, MA',
    currentResidence: 'Boston, MA',
    familyDetails: 'Living with the girlfriend Francoise, and my Australian Shepherd Alta.',
    occupation: "Master's Student (Engineer)",
    startTriathlon: 'I started doing triathlon January of 2022. I went to school at Arizona State University and every fall would witness the two Ironman races which took place right on the edge of campus. At the time I was invested in Crossfit and had a great community so I never had the push to start triathlons. After finishing school and moving back to Massachusetts I made the spontaneous decision to start triathlon and never looked back!',
    preferredDistance: 'Half Ironman',
    highlights: 'Goal for 2023 season was to finish sub 5 hours in a race, which I did all three 70.3s of the season and placed 3rd in my age group two of the three races.',
    interests: 'Skiing, remote camping, traveling',
    goals: 'I hope to meet and build long lasting relationships with other team members. Find potential training partners and help push each other to reach out short and long term goals.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/EvanCoronado.jpg'
  },
  {
    fullName: 'Colin Cook',
    hometown: 'Pepperell, MA',
    currentResidence: 'Brookline, NH',
    familyDetails: 'Spouse: Kristen (married since 2012) 4 children: Calvin (11), Elijah (9), Gabriel (7), Ruby (6) 1 dog: Rosa.  ',
    occupation: 'Technical Account Manager',
    startTriathlon: '2009',
    preferredDistance: 'Ironman',
    highlights: '19x Ironman Finisher, 7x Ironman World Championships Finisher, 2020 Ironman Florida Overall Amateur Champion, 2023 M40-44 Sprint Distance National Champion, 2023 Maine 70.3 Overall Amateur Champion, many Ironman and 70.3 Age Group wins. ',
    interests: 'Coaching flag football, traveling, spending time with my family.',
    goals: 'Win my age group at Ironman Lake Placid, qualify for Kona, win White Mountains Triathlon, Win Age Group National Championship, finish in under 9 hours in Kona.',
    additionalInfo: 'I have a drug and alcohol background.  However, thanks to my wife and triathlon, I have found a way to overcome that addition and regain control of my life.  I have a true passion for triathlon and living a healthy lifestyle.  I thoroughly enjoy helping others to pursue their passions and find balance in their lives.  I also co-host the Age Grouper For Life Podcast.',
    pictureUrl: '/images/ColinCook.jpg'
  },
  
  {
    fullName: 'Taylor Days-Merrill',
    hometown: 'Millis, MA',
    currentResidence: 'Millis, MA',
    familyDetails: 'Jess Days-Merrill (Wife)',
    occupation: 'Pharmacist',
    startTriathlon: '2021. Parents met in Kona. I grew up running, but knowing triathlon was the end game',
    preferredDistance: 'Ironman',
    highlights: '76th at 2018 Boston Marathon, All-New England for College 10k, 2nd, 3rd, and 4th place finishes at consecutive Maine Marathons, 2nd at Maine Coast Marathon, 1st at 2023 White Mountain Half.',
    interests: 'Hiking and snowboarding',
    goals: 'Improve as a triathlete, and gain racing experience.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/TaylorDays-Merrill.jpg'
  },
  {
    fullName: 'Hans Larsson',
    hometown: 'Norrköping, Sweden',
    currentResidence: 'New Boston, NH',
    familyDetails: 'My wife and best friend Bonnie',
    occupation: 'Product Line Engineer, Capital Install Engineer ',
    startTriathlon: '2014 - tore my adductor playing ice hockey training for a marathon.  Finding ways to keep fitness and found swimming and biking was painless. Got involved in a local group who coaxed me into my first sprint and half Ironman ',
    preferredDistance: 'Ironman',
    highlights: 'After 5 full Ironman distance races chasing my Kona slot and finally clinched my spot to Hawaii in 2019. ',
    interests: 'Cross country skiing.  Traveling with my wife to warm destinations. Big foodie and enjoying life in general. ',
    goals: 'Build my network of triathlon friends and race with some fast team mates. KQ at IMLP would be nice too 😊',
    additionalInfo: 'N/A',
    pictureUrl: '/images/HansLarsson.jpg'
  },
  {
    fullName: 'Rich Uliana',
    hometown: 'Pen Argyl, PA',
    currentResidence: 'Nazareth, PA',
    familyDetails: 'Spouse - Meghan, Daughters - Ava (15), Mia (13), Ali (12). 2 dogs and a cat',
    occupation: 'Sales Leader',
    startTriathlon: 'Did my first race in 2017. I lost both of my parents to cancer earlier that year. I turned to triathlon as a way to cope and deal with the stress.',
    preferredDistance: 'Half Ironman',
    highlights: 'Kona Qualification at IMCHOO, 2022',
    interests: 'Downhill skiing, SUP, anything outside',
    goals: 'Podium finishes at Eagleman and IMLP. Represent the team well in Kona',
    additionalInfo: 'Just happy to have the opportunity to be a part of the next best team in triathlon!',
    pictureUrl: '/images/RichUliana.jpg'
  },
  {
    fullName: 'Carley Gross',
    hometown: 'Orange County, CA',
    currentResidence: 'Wichita, KS',
    familyDetails: 'Parents and 2 older brothers ',
    occupation: 'KC135 Pilot',
    startTriathlon: 'I dabbled a little in high school but really committed in college when I joined the club team. The sense of family, drive to excel over three disciplines,  and healthy competition is what keeps me coming back!',
    preferredDistance: 'Half Ironman',
    highlights: "I've raced over 12 half iron distance races. I've qualified for four 70.3 World Championships and competed at 2 with the third next year. I'll also be competing at the World Triathlon Multisport Championships this year.",
    interests: 'I volunteer on weekends at a rescue ranch for horses. With over 65 horses they take a lot of looking after while they await new homes! I also love outdoors sports, skiing, snowboarding, water sports, hiking, camping, etc. Anything that gets me out and into the wild!',
    goals: 'My goal this year is to crack top 50 on the world stage in my age group in New Zealand and in Australia! In regional races, I am aiming to claim the W on the podium for the 70.3 I race in.',
    additionalInfo: 'I am hoping to add more races to the calendar for 2024, but there will be a lot of last minute sign ups. I am stoked to be competing with Top Gunz Tri Team and cannot wait to celebrate the friends and family from this triathlon community!',
    pictureUrl: '/images/CarleyGross.jpg'
  },
  {
    fullName: 'Mark Castrovinci',
    hometown: 'New Canaan, CT',
    currentResidence: 'Lexington, MA',
    familyDetails: 'Wife: Susannah, Son: Thomas, Dog: Bravo',
    occupation: 'Assistant Manager at Marathon Sports',
    startTriathlon: 'In 2012 because I wasn’t rowing anymore and needed something to stay in shape.',
    preferredDistance: 'Ironman',
    highlights: 'Going under 4:30 at Maine 70.3 and coming in 5th to qualify for WC. Running a 3:30 at IMLP to get me to qualify for Kona, and then competing in Hawaii.',
    interests: 'Skiing',
    goals: 'Qualify for Kona and hopefully go sub in lake placid. ',
    additionalInfo: 'I open mouth kissed a horse once.',
    pictureUrl: '/images/MarkCastovinci.jpg'
  },
  {
    fullName: 'Matt Nussbaum',
    hometown: 'Stamford, CT',
    currentResidence: 'Boston, MA',
    familyDetails: 'Wife Naomi and Dog Arthur',
    occupation: 'Engineer',
    startTriathlon: 'I did a sprint in 2016 wanting to try a tri before turning 25. I had no idea what I was getting myself into.',
    preferredDistance: 'Half Ironman',
    highlights: 'Getting a Kona slot at my first full Ironman and then beating that finish time by a huge margin in Hawaii. Working my way to the overall podium at my favorite local race. Finishing 4th overall for an IM70.3 in a tropical storm.',
    interests: 'Skiing',
    goals: 'Win the local half, find the podium at IM Lake Placid, and get a 70.3 PR at IM70.3 New York.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/MattNussbaum.jpg'
  },
 
  {
    fullName: 'Marc Schwartz',
    hometown: 'Richmond, VA',
    currentResidence: 'Cambridge, MA',
    familyDetails: 'Wife - Jenny, Kids - Luke (7), Wesley (5), Madison (3)',
    occupation: 'Physician Scientist',
    startTriathlon: 'Invited by a friend to do a sprint triathlon in 2010, have loved it every since.',
    preferredDistance: 'Ironman',
    highlights: '2 overall race wins at local olympic distance events in 2012, first ironman finish at IMAZ 2023 in 9:35',
    interests: 'Backpacking, packrafting, ski touring. Adventuring outside with kids.',
    goals: 'Age group podium/qualify for worlds at IMAZ. Guide my sister to her first triathlon finish in paratriathlete category.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/Marc1.jpg'
  },
  {
    fullName: 'Patrick McDeed',
    hometown: 'Merriman, NH',
    currentResidence: 'Washington, DC',
    familyDetails: 'Son, Younger Brother, Co-parenting two dogs and a cat',
    occupation: 'PhD Candidate in Biostatistics at Georgetown University',
    startTriathlon: 'I started my journey into endurance sport in college as a way to get healthy and make some lifestyle changes. What started as a few after work runs with a coworker led to my first 5k, and the rest is history. Things quickly snowballed from there and before I knew it I had run a handful of marathons! With such rapid progression in distance, I naturally ended up injured, leading to a return to my childhood roots in the pool and some time on the spin bike to cross train. Once fully healthy I decided to throw all three sports together and try my first triathlon. Much like my experience with running, the support from the broader community and the never ending quest to find my personal limits was infectious. Reaching for goals I never dreamed were even possible when I was younger fuels me with excitement to train and better myself each and every day.',
    preferredDistance: 'Ironman',
    highlights: 'Returning from a broken collarbone to compete in my first Ironman World Championships in Kona. It was an incredible experience to cap off a very trying few weeks leading up to the race.',
    interests: "As much as I like generating my own data from swim-bike-run, I love analyzing it! Whether it's nerding out on my academic research or diving into topics in sport science. Away from training and numbers, I enjoy time outdoors in the mountains, unwinding on the yoga mat, and giving back to my multisport community, wearing many hats across the groups I'm involved in.",
    goals: 'Be curious.',
    additionalInfo: 'N/A',
    pictureUrl: '/images/PatickMcDeed.jpg'
  },
  {
    fullName: 'Sloane Tilley',
    hometown: 'Cary, NC',
    currentResidence: 'Washington, DC & Newark, NJ',
    familyDetails: "Husband of 7.5 years - Nate Tilley and our two GSPs - Levin and Penelope! Levin is named after Anna Karenina and Penelope is named after Odysseus's wife",
    occupation: 'CEO of my own fledgling start-up ',
    startTriathlon: 'I started doing triathlon my senior year of college as a way to get involved with an awesome group of other female STEM graduate students. It was a way to carve out social time while de-stressing in a healthy way.',
    preferredDistance: 'Half Ironman',
    highlights: "My first race back after I had a big accident when they weren't sure if I would be able to race again; finishing my first full Ironman; winning my first overall local podium",
    interests: 'Watching Carolina sports, reading, baking, & traveling',
    goals: '(1) Qualify for Boston 2025 (2) Qualify for IM 70.3 WC in Taupo (3) Have a fun race in beautiful New Zealand! ',
    additionalInfo: 'N/A',
    pictureUrl: '/images/Tilley.jpg'
  },
  {
    fullName: 'Caleb Samuel McVey',
    hometown: 'Manchester, NH',
    currentResidence: 'Concord, NH',
    familyDetails: 'Girlfriend - Sydney Carter, Cats - Salem, Gaea, and Zoey',
    occupation: 'Fedex Driver',
    startTriathlon: 'I competed in my first race in June of 2022. After a pretty bad concussion in 2020 playing soccer I was looking for low impact, but competitive and challenging, physical outlets to fill that void and found Triathlon. ',
    preferredDistance: 'Olympic',
    highlights: '1 Overall Olympic distance win(NH State Champion) 1 70.3 world championship Qualification(2024) ',
    interests: 'I play Magic the Gathering competitively. I love hiking and taking pictures of the outdoors.',
    goals: 'There are countless people in my life that have been by my side and helped me throughout the years; I can never say thank you enough for the support. Though small, giving nothing less than my best effort on race day is one of the ways I show my appreciation and gratitude to everyone who has had a hand in me getting to the start line.   “To give anything less than your best, is to sacrifice the gift” - Steve Prefontaine ',
    additionalInfo: 'Listen to Black Cats Run Podcast ',
    pictureUrl: '/images/CalebMcVey.jpg'
  },
  {
    fullName: 'Amanda Quinlan',
    hometown: 'Antrim, NH',
    currentResidence: 'Manchester, NH',
    familyDetails: 'The best rescue dog ever, Frankie!',
    occupation: 'Attorney',
    startTriathlon: "I did a few sprints here and there after 2015, but didn't really get going until my first 70.3 in 2022. I've always been a runner and this was a way to diversify training and get better at something new!",
    preferredDistance: 'Half Ironman',
    highlights: 'Qualifying for Kona after my first Ironman, PRing at Boston twice!',
    interests: 'Hiking the White Mountains, trail running, hanging with my best pal Frankie! ',
    goals: 'PR in the 70.3! And get faster on the bike!',
    additionalInfo: 'I love that I get to be a part of a team for what is still a new sport for me!',
    pictureUrl: '/images/AmandaQuinlan1.jpg'
  },
  {
    fullName: 'Matt Schuster',
    hometown: 'Long Island, NY',
    currentResidence: 'Glen Rock, NJ',
    familyDetails: 'My wife Rachel and I have been married for 12 amazing years. We have two boys, Jack 8 and Max 5 and our first child, Howie a 10 year old whippet/shepard mut that loves to snuggle. ',
    occupation: 'After spending 15 years as a Madison Avenue ad exec, I made a career pivot to pursue my entrepreneurial roots in the endurance sports space. More to come soon. ',
    startTriathlon: 'I found triathlon in 2020 as part of my mid life Renaissance. I had spent the previous 10 years nearly dormant of all fitness. This had profoundly negative effects on my health not only physically, but in many ways more mentally. In the fall of 2019 after years of self inflicted mental torment, I experienced what I can only describe as a complete burnout. My work abilities, physical state and self confidence had been ground down to dust. At the lowest point, getting out of bed in the morning was a monumental task.  I stepped away from work and after suffering through a local turkey trot in Nov 2019, I decided it was time for a reset and I would start by focusing on my physical health first. It started with basic exercise, then running, bike rides and ultimately after a suggestion by my sister, triathlon.  I immediately started with structured coaching and can honestly say, it completely changed my life. For the first time I had a structure and discipline that was dedicated solely to my own self development. Everyday I would get a little better, a little stronger and mentally a little healthier.  Today, training and fitness is a core value in my lifestyle, and cant even imagine how I survived prior. ',
    preferredDistance: 'Half Ironman',
    highlights: 'Two top 10 overall and five AG podiums in the Ironman 70.3 Distance. 7th overall at the inaugural Ironman New York 70.3 at Jones Beach. 2 time USAT All American ',
    interests: "I'm a parent, Entrepreneur and Triathlete... not much time for much else these days haha. Though when I do get a free second, I love playing the guitar, though not very well : ) ",
    goals: 'I learned a hard lesson in 2023, things rarely work out when you chase results. So for 2024 my goals are very process focused.  - Nail the elevation specificity in the training leading up to placid, including at least one Everest week during the build.   - Build up to and be able to absorb 23 hour/1400 TSS training weeks - Train towards a sub 3:10 Ironman run and sub 1:20 70.3 run - Improve 70.3 NP by 15- 25 watts - Out of the water inside of 4 minutes in 70.3 and 10 min in Ironman of the race leader ',
    additionalInfo: 'I am very excited to be racing with TopGunz this year. Being connected to such an incredible group of high achieving individuals has been a game changer. Motivating me to push harder, challenging me on what I thought was possible and sharing lessons learned on proper life balance. This team is not just athletes, they are all around elite humans. ',
    pictureUrl: '/images/Schuster.jpg'
  },
  {
    fullName: 'Kyle Jones',
    hometown: 'Bedford, NH',
    currentResidence: 'Boston, MA',
    familyDetails: 'I have an amazing family who I love spending time and making memories with. I grew up in Bedford, NH, where my Mother and Father currently reside. These days, I live in Boston, MA with my wonderful girlfriend Abby. My younger sister, Courtney, also lives in Boston with her husband Colin, just a few blocks away from me. My older sister, Meghan, lives in Texas with her husband Chad, my two nieces, Ella & Savy and my nephew Gage.',
    occupation: 'Software sales professional',
    startTriathlon: '2After spending a few years as a marathoner, my father got me into triathlon in the spring of 2022. I originally began the sport because I was looking for a challenge. Triathlon is now a big part of my life and a catalyst for pursuing my full potential.',
    preferredDistance: 'Ironman',
    highlights: '7th in age group at Ironman Maryland',
    interests: 'Hiking, Snowboarding, Golfing, Traveling, Archery ',
    goals: 'Qualify for the Ironman World Championship in Kona, Hawaii',
    additionalInfo: 'N/A',
    pictureUrl: '/images/KyleJones.jpg'
  },
  {
    fullName: 'Steph Cummings',
    hometown: 'Llidiartywaen, Wales ',
    currentResidence: 'Cornish, NH',
    familyDetails: 'My incredible Sherpa, Adam and our 9 year-old Brittany Spaniel, Copper! ',
    occupation: 'Records and Service Specialist for the Dartmouth Geisel School of Medicine',
    startTriathlon: "I began my triathlon journey in January 2022 with no swimming or biking experience. I've always loved to challenge myself and push me out of my comfort zone. Traithlon was originally an event on my bucket list.",
    preferredDistance: 'Half Ironman',
    highlights: "(2022)  2nd AG - Partriot Half with a 37' 70.3 PR, 10th AG - Ironman Maine 70.3, 1st AG - Cranberry Trifest Olympic Distance, 7th AG - Ironman 70.3 Michigan",
    interests: 'Baking, gardening, interior design, construction. Huge love for animals! ',
    goals: 'To podium at my Ironman 70.3 events, finally crack a sub 1:30 half marathon, and a sub 4:45 for the 70.3 distance. ',
    additionalInfo: 'Throughout my life I have dealt with some serious mental health issues. These demons have ranged from negative self talk, depression to failed suicide attempts. It has taken me a long time to accept my past, but now I am in a position to use it as a platform for how I have and continue to transform my life. Triathlon plays a huge role in keeping me physically and mentally healthy! The incredible camaraderie around triathlon is the best support network I could wish for!',
    pictureUrl: '/images/StephCummings.jpg'
  },
  
 
  {
    fullName: 'Susanne Carpenter',
    hometown: 'Nashua, NH',
    currentResidence: 'Nashua, NH',
    familyDetails: 'My ultrarunner husband of almost 23 yrs, Jeff...who is my biggest cheerleader.  Two incredible twentysomething kids, Griffin & Grace.  Two sometimes hyper, sometimes lazy, mostly smelly and always hilarious Frenchies, Milo & Hazel',
    occupation: "I'm a professionally trained Pastry Chef. I have my own business, Le Petit Whisk, where I teach recreational pastry classes.",
    startTriathlon: "I did my first sprint triathlon in 2007.  I had just run the Boston Marathon and was looking for a new challenge.  I did not come from a swimming or cycling background so I was really starting from ground zero but that is what made it a great challenge. After that first sprint, I wasn't necessarily hooked on the sport until 2018 when repeated running injuries forced me to swim & bike more.",
    preferredDistance: 'Half Ironman',
    highlights: 'BQ x 5,  Marathon PR at Chicago in 2019 (3:23:51).  2nd in my AG at my first 70.3 (PumpkinMan 5:22), 6th in my AG at my first IM and qualified for Kona (Mont Tremblant 12:18:43)',
    interests: 'Outside of triathlon I absolutely love baking. Whether it is for work or pleasure working with my hands to create pastries or breads brings me so much joy.  Second to baking I love to spend my down time reading and gardening.',
    goals: 'Big goal is to PR in the IM distance and qualify for Kona again, as well as be top 3 in my AG for a 70.3',
    additionalInfo: 'I am really excited to be part of the Top Gunz Triathlon Team.  There are a lot of younger, extremely talented, incredibly fast athletes in this group, but I hope to show others that age is just a number and you can still be competitive after 50.',
    pictureUrl: '/images/SusanneCarpenter.jpg'
  },
  {
    fullName: 'Tim Ryan',
    hometown: 'New Jersey',
    currentResidence: 'Boston, MA',
    familyDetails: 'N/A',
    occupation: 'Product Research Manager at DraftKings',
    startTriathlon: "It was mostly an accident. As a former college swimmer I got asked to be on the relay of several triathlons, so I was exposed to the sport that way. I had a bike, which I got for my birthday when my dad took up cycling, so we could ride together. I played soccer through high school, so I was an okay runner, but didn't do running races until after college when I was tired of being my brothers's race sherpa. I did a triathlon or two after that, but never considered myself a triathlete. Then in business school a friend of mine who was a triathlete knew that I had done one so we started to train for fun. It wasn't until I moved to Boston that I decided to keep the training going and use the sport to meet people. Then I got hooked during the pandemic and haven't stopped training since!",
    preferredDistance: 'Half Ironman',
    highlights: 'Qualifying for Team USA (Olympic Distance), Ironman 70.3 Worlds, and Ironman Worlds in the same year.',
    interests: 'Whiskey fan - in 2023 I tried over 100 different kinds. I dabble in custom painting shoes - hope to get going on my TopGunz pair soon. I have patio garden that I enjoy working in. I have a lemon tree that actually produces lemons!',
    goals: 'Process Goals: Early to swim starts (no dawdling in transition), consistent lifting throughout the year, get nutrition+body in a place to be able to flying dismount at a 70.3 | Race/performance goals: run sub 1:30 off the bike in a 70.3, top 3 AG finish at a 70.3 [4th is highest]',
    additionalInfo: 'N/A',
    pictureUrl: '/images/TimRyan.jpg'
  },
  {
    fullName: 'Mike Consolini',
    hometown: 'Springfield, MA',
    currentResidence: 'Agawam, MA',
    familyDetails: 'I have a wife, Melissa, and two daughters, Ellie and Lucy. Ellie is 4.5 years old, and Lucy is just shy of 3. Needless to say, we are kept very busy and on our toes! ',
    occupation: 'I am a firefighter/paramedic for the Town of Agawam MA, and I have been in EMS for almost 20 years, starting out as an EMT.',
    startTriathlon: 'I was thrown into my first sprint triathlon in 2014, that a local Tri club was hosting by my now wife who had been doing tris for a few years. It was quite an experience, as I signed up on the morning of with no actual training prior. That same summer, I went with my wife and our local Tri club, Cyclonaut Multisport, to Ironman Lake Placid as a spectator. I was blown away by the whole vibe during the week, the gear, and how these people were completing something that seemed so hard and nearly impossible. I said to myself that week I would really love to do this someday.  After joining the club myself, I began to focus on running and doing some real training for a marathon. It had been a lifelong dream of mine to qualify for the Boston Marathon someday, and I managed to achieve that in my second attempt. It felt pretty emotional running into Boston past the big Citgo sign for the first time. After a couple of years of marathon racing and training I had the confidence to go back and give triathlon another try. IIn 2018 I signed up for IMLP and my triathlon journey began. I do it for a very similar reasons which drove me to begin running. I love the challenge of doing something hard and building self discipline. I love how it makes me feel everyday during and after training. I love the idea of being an athlete and being fit. It gives me direction and keeps me out of trouble as well. I also seem to inspire my family, friends, coworkers and those around me with my racing, training and lifestyle which is very special to me.',
    preferredDistance: 'Ironman',
    highlights: 'A big highlight for me was placing third AG/10th overall at my first Ironman 70.3 in 2018 at Syrcause, qualifying me to the 70.3 World Championships in South Africa. Truthfully though, my biggest career highlight to date was running 6 miles alongside Magnus Ditlev in IM Florida this year. It felt pretty surreal. Not only is he world class, but he is truly such a kind and humble guy. ',
    interests: 'My faith and involvement in my local church, Hope Community Church is very important to me. I also love art and music. I play bass guitar in church, and played in bands growing up. These days I’m mostly just strumming along to the wheels on the bus on my acoustic at home with the kiddos.',
    goals: 'My 2024 goals are mostly just overall improvement in training, racing, and personal performance. The big goal for is having a race to be proud of in Lake Placid, and hopefully qualifying to the 2024 Ironman World Champs in Kona! ',
    additionalInfo: 'I am very honored and grateful to be a part of this team! ',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Kyle Axman',
    hometown: 'Atlantic Beach, NY',
    currentResidence: 'New York, NY',
    familyDetails: 'Just married on Dec 2, 2023!',
    occupation: 'Sales/Brand Partnerships Therabody + Fitness Entrepreneur Lifetime/Rumble Training/Personal',
    startTriathlon: 'I started racing six years ago. I only started endurance sports around then when I began my group fitness career in indoor cycling in 2016. My father was a triathlete growing up and traveled the world as the podiatrist for the USA tri team. My whole life, my father would tell me tri stories, but, in all honesty, I never really listened. I fell in love with the sport and realized it was in my blood. I originally raced to make my father proud and that is why I continue to do so. ',
    preferredDistance: 'Half Ironman',
    highlights: 'Sub 3 marathon, 1:20 half marathon, Winning age group in a sprint and 2nd overall, 4:47 Ironman 70.3. Doing a relay sprint with my father and uncle. ',
    interests: 'group fitness, travel, ice cream',
    goals: 'Elevate my game and do better than last season. Learn from some of the greats and lean on the community for motivation.',
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Alex Kramer',
    hometown: 'East Northport, NY',
    currentResidence: 'Malden, MA',
    familyDetails: 'Engaged',
    occupation: 'Analytical Chemist',
    startTriathlon: 'Summer of 2021. I was training for the Chicago marathon, and doing some extra biking to supplement my training. There was a local triathlon that summer, and I had always wanted to try it out. So I started doing a swim 2-3 times a week at the beach near my parent’s house. Raced my first sprint distance triathlon. And had a lot of fun! I ended up getting injured and having to drop out of the Chicago marathon. So when I started training again, i didn’t want to keep doing 100-120 mile weeks of running after getting injured . So I thought I’d try training for triathlon’s and I haven’t stopped since.',
    preferredDistance: 'Half Ironman',
    highlights: '2nd Place overall at the Vermont Sun Olympic Distance State Championships Triathlon June 2022. 3rd place overall in the Max Performance Harvest Triathlon. 5th Place overall and top in age group at Musselman 70.3 ',
    interests: 'Hiking, Rock Climbing, Snowboarding',
    goals: 'Finish Top in my age group at Maine 70.3 2024. Finish top in my age group at USAT Nationals (Olympic Distance). Earn USAT Elite status.',
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Brian Reynolds',
    hometown: 'Kalamazo, MI',
    currentResidence: 'Richland, MI',
    familyDetails: 'Engaged, no children',
    occupation: 'Mechanical Engineer',
    startTriathlon: 'I wanted to do a triathlon since I was 12 years old. The Olympic triathlon in the 2000 Sydney Olympics and the Ironman in Hawaii were the races that inspired me..',
    preferredDistance: 'Half Ironman',
    highlights: '2022 & 2023 Ironman Texas 70.3 Overall Winner',
    interests: 'Watching the Detroit Lions',
    goals: 'Learn from my teammates and sponsors.',
    additionalInfo: 'Racing as a professional for the 2024 season',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Steven Meng',
    hometown: 'Northville, MI',
    currentResidence: 'Chapel Hill, NC',
    familyDetails: 'N/A',
    occupation: 'Data Scientist',
    startTriathlon: 'Raced my first tri in fall of 2018. Started because I wanted a way to stay fit outside of tennis during college. Found running, then trained and raced a marathon on a whim. Swore to never run a marathon again (oh, the irony) and started triathlon training since the standard race run distance was only 10km, I knew how to bike, and how hard could it be to learn how to swim? (Oh, the irony again)',
    preferredDistance: 'Half Ironman',
    highlights: 'Fastest time and highest placement at 70.3 Michigan 2022. 19th overall, 4th in 18-24 AG, 4:28 total time',
    interests: 'Hiking, national parks, cooking, tennis, golf',
    goals: 'Connect and race with all the talented triathletes on the team. Push the most out of myself and inspire other athletes and the community to stay active and healthy',
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1ABCD1234EFGH...',
},
{
  fullName: 'Sherri Brown',
  hometown: 'Wells, ME',
  currentResidence: 'Wells, ME',
  familyDetails: 'Married to an amazing Sherpa, Steve and we are fortunate to have our adult children and their families living close by.  We love fun family adventures all the more these days with the newest addition to the family, our grandson.',
  occupation: 'VP of Operations',
  startTriathlon: 'I started triathlon in 2018 as I set out on a journey to get stronger and to live a healthy lifestyle',
  preferredDistance: 'Half Ironman',
  highlights: '4X Boston Qualifier, Ironman Lake Placid Kona Qualifier, Maine 70.3 3rd in age group, Patriot 1st in age groups: 6 Years racing as a Professional Triathlete 3rd Overall at Ironman 70.3 Lima (2023) 2nd Overall at Sea to Summit Triathlon (2023) *Bike Course Record 1st Overall at Boston Triathlon (2023) 1st Overall at Ironman 70.3 Puerto Rico (2022) 1st Overall at Ironman 70.3 Desaru Coast (2022) 1st Overall at 70.3 Patriots (2021) 1st Overall at the Hyannis 10K (2020) 1st Overall at the Chicago 10K (2018) 1st Overall at the Chicago Triathlon (2018)',
  interests: 'Gravel biking, family adventures and spending time in the mountains',
  goals: 'We all have our own individual goals but being a part of the Top Gunz team brings working towards those goals to a whole new level. Working together will help bring out the best in each of us with a strong emphasis on not only training and racing, but to represent all the team stands for, including living a healthy well balanced lifestyle.  I hope to represent that well both on and off the race course.',
  additionalInfo: 'Although I am newly diagnosed with a heart condition that may limit my ability to compete as well as I would like to and my goals are a little different these days, I still hope to continue on the Ironman journey and give it my best shot.',
  // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
},
{
  fullName: 'Breno Melo',
  hometown: 'Boston',
  currentResidence: 'Boston',
  familyDetails: 'Theo, golden puppy 🐶',
  occupation: 'Software sales',
  startTriathlon: '2011',
  preferredDistance: 'Half Ironman',
  highlights: 'Athletic Highlights: 6 Years racing as a Professional Triathlete 3rd Overall at Ironman 70.3 Lima (2023) 2nd Overall at Sea to Summit Triathlon (2023) *Bike Course Record 1st Overall at Boston Triathlon (2023) 1st Overall at Ironman 70.3 Puerto Rico (2022) 1st Overall at Ironman 70.3 Desaru Coast (2022) 1st Overall at 70.3 Patriots (2021) 1st Overall at the Hyannis 10K (2020) 1st Overall at the Chicago 10K (2018) 1st Overall at the Chicago Triathlon (2018)',
  interests: 'Wine sommelier',
  goals: 'Survive and thrive',
  additionalInfo: 'I’ve gained weight',
  // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
},
  {
    fullName: 'Kyle Bergman',
    hometown: 'New York City, NY',
    currentResidence: 'Severna Park, MD',
    familyDetails: 'Wife Elizabeth, and two baby twin boys Max + Bernie (Born October 2023). ',
    occupation: 'Entrepreneur',
    startTriathlon: '2021 - a friend asked me to do the Arizona 70.3 with him. ',
    preferredDistance: 'No preference',
    highlights: '6 70.3s and 1 Full...and I continue to get faster in each race. ',
    interests: 'Ice tubs, ecommerce, growth hacking',
    goals: 'Continue to get faster. Win the 70.3 and Full Maryland Ironman Events',
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Owen Wurzbacher',
    hometown: 'Seattle, WA',
    currentResidence: 'Boston, MA',
    familyDetails: 'Hillary Wurzbacher (wife), Olive Wurzbacher (daughter), Ruth (dog)',
    occupation: 'Investment Management',
    startTriathlon: '18 months ago because a friend encouraged me to',
    preferredDistance: 'Half Ironman',
    highlights: 'N/A',
    interests: 'Reading',
    goals: 'Get better',
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },
  {
    fullName: 'Ginger Howell',
    hometown: 'Natick, MA',
    currentResidence: 'Natick, MA',
    familyDetails: 'I live alone; am in a long-distance relationship',
    occupation: 'Swim instructor',
    startTriathlon: 'I started swimming in high school, and got interested in running in college, after watching the Boston Marathon.  One of my friends told me, "You are a swimmer.  You are a marathoner.  Biking is the easy part.  You should do an Ironman!"  I replied, "112 miles of anything is not easy!" However, I have never been one to turn down a challenge, and shortly after that, I signed up for the Louisville Ironman.  I had never done a sprint tri, and did not own a bike, but I had a year to take care of those little details.  That was 2009.  I finished in 11:32, but totally burned myself out in the process.  I got back into it in 2014, and have been taking it pretty seriously since then. ',
    preferredDistance: 'Ironman',
    highlights: 'I raced Kona as an age grouper in 2016 and 2017, and turned pro in 2018.  I won the Boston Triathlon in 2019 & 2021.  In 2023 I was excited to get 3rd at the NYC Tri and 4th at the Escape from Alcatraz Triathlon.',
    interests: 'I used to teach classes with a youth circus program!',
    goals: "I actually signed up for the inaugural Race Across the East - a 630-mile continuous bike race from Ohio to New Jersey (last 20% of RAAM).  Besides that, I'm looking at the White Lake Half, possibly Alcatraz, a couple of local 70.3s, and I'd like to do a full distance Ironman but am not sure which one yet!",
    additionalInfo: 'N/A',
    // pictureUrl: 'https://drive.google.com/open?id=1YVYLEVEu9VYY...'
  },

  // Add more athlete objects here
];

const AthleteProfiles = () => {
  return (
    <div className="athlete-profiles">
      {athleteData.map((athlete, index) => (
        <AthleteProfile key={index} athlete={athlete} isOdd={index % 2 !== 0} />
      ))}
    </div>
  );
};

export default AthleteProfiles;
